[profile.default]
solc = '0.8.17'
via_ir = true
src = 'contracts'
out = 'out'
libs = ["node_modules", "lib"]
test = 'test/foundry'
remappings = [
    'ds-test/=lib/ds-test/src/',
    'forge-std/=lib/forge-std/src/',
    '@rari-capital/solmate/=lib/solmate/',
    'murky/=lib/murky/src/',
    'openzeppelin-contracts/=lib/openzeppelin-contracts/',
    'seaport/=contracts/',
]
fuzz_runs = 5000
fuzz_max_global_rejects = 2_000_000
optimizer_runs = 5500
fs_permissions = [
    { access = "read", path = "./optimized-out" },
    { access = "read", path = "./reference-out" },
]
extra_output = ["evm.assembly", "irOptimized", "devdoc"]

[profile.default.optimizer_details]
peephole = true
inliner = true
jumpdestRemover = true
orderLiterals = true
deduplicate = true
cse = true
constantOptimizer = true

[profile.default.optimizer_details.yulDetails]
stackAllocation = true
optimizerSteps = "dhfoDgvulfnTUtnIf[xa[r]EscLMcCTUtTOntnfDIulLculVcul [j]Tpeulxa[rul]xa[r]cLgvifCTUca[r]LSsTOtfDnca[r]Iulc]jmul[jul] VcTOcul jmul"


[profile.reference]
solc = '0.8.13'
via_ir = false
src = 'reference'
out = 'reference-out'
script = 'reference'
# specify something so it doesn't try to compile the 0.8.17 files in test/foundry
test = 'reference'

[profile.optimized]
out = 'optimized-out'

[profile.test]
via_ir = false
src = 'test/foundry'

[profile.lite]
out = 'optimized-out'
via_ir = false
fuzz_runs = 1000

[profile.local]
via_ir = false
fuzz_runs = 1000
src = 'reference'
out = 'reference-out'

[profile.offerers]
src='offerers'
test='offerers'
out = 'offerers-out'
script = 'offerers'
via_ir = false
fuzz_runs = 1000

[fmt]
line_length = 80
tab_width = 4
bracket_spacing = true

# See more config options https://github.com/gakonst/foundry/tree/master/config
